export interface Precedent {
  id: number
  title: string
  citation: string
  year: number
  bench: string
  category: string
  tags: string[]
  principle: string
  holding: string
  applicability: string
  approved: boolean
  area: string
}

export const PRECEDENTS: Precedent[] = [
  {
    id: 1,
    title: "Kesavananda Bharati v. State of Kerala",
    citation: "AIR 1973 SC 1461 · (1973) 4 SCC 225",
    year: 1973,
    bench: "13-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Fundamental Rights"],
    principle: "Basic Structure Doctrine — Parliament cannot amend the Constitution so as to destroy its basic structure including judicial review, rule of law, separation of powers, and fundamental rights.",
    holding: "The power of Parliament under Article 368 does not include power to abrogate or emasculate the basic elements or fundamental features of the Constitution.",
    applicability: "Binding on all courts in India. Applied in all cases involving constitutional amendments, judicial review of legislative action, and fundamental rights challenges.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 2,
    title: "Maneka Gandhi v. Union of India",
    citation: "AIR 1978 SC 597 · (1978) 1 SCC 248",
    year: 1978,
    bench: "7-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Article 21", "Fundamental Rights", "Personal Liberty"],
    principle: "Article 21 is not limited to mere physical existence — the procedure established by law must be just, fair, and reasonable. Articles 14, 19 and 21 are not mutually exclusive.",
    holding: "The expression 'procedure established by law' in Article 21 must be right, just, fair and not arbitrary, fanciful or oppressive.",
    applicability: "Binding on all courts. Fundamental in any case involving deprivation of life or personal liberty. The expanded interpretation of Article 21 applies across criminal, civil, administrative, and public law matters.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 3,
    title: "Bachan Singh v. State of Punjab",
    citation: "AIR 1980 SC 898 · (1980) 2 SCC 684",
    year: 1980,
    bench: "5-Judge Constitution Bench",
    category: "criminal",
    tags: ["Criminal Law", "Death Penalty", "Sentencing"],
    principle: "Death penalty is constitutionally valid but must be awarded only in the 'rarest of rare' cases after weighing aggravating and mitigating circumstances.",
    holding: "Section 302 IPC providing death penalty is not violative of Articles 19 and 21. The rarest of rare doctrine governs sentencing discretion.",
    applicability: "Binding on all criminal courts. Applied mandatorily in all capital punishment sentencing. High Courts must apply the rarest of rare test before confirming death sentence.",
    approved: true,
    area: "Criminal Law",
  },
  {
    id: 4,
    title: "Vishaka v. State of Rajasthan",
    citation: "AIR 1997 SC 3011 · (1997) 6 SCC 241",
    year: 1997,
    bench: "3-Judge Bench",
    category: "constitutional",
    tags: ["Constitutional", "Women Rights", "Workplace"],
    principle: "Sexual harassment at workplace violates Articles 14, 19 and 21. Every employer must have a Sexual Harassment Committee and detailed redressal mechanism.",
    holding: "Vishaka Guidelines laid down as binding law until legislative enactment. Now superseded by POSH Act 2013.",
    applicability: "Binding on all courts and employers. High Courts apply while examining POSH Act compliance and workplace harassment matters.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 5,
    title: "S.R. Bommai v. Union of India",
    citation: "AIR 1994 SC 1918 · (1994) 3 SCC 1",
    year: 1994,
    bench: "9-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Federalism", "Article 356"],
    principle: "Presidential Proclamation under Article 356 is subject to judicial review. Secularism and federalism are part of the basic structure of the Constitution.",
    holding: "Imposition of President's Rule under Article 356 is subject to judicial review. Majority must be tested on floor of the House.",
    applicability: "Binding on High Courts in all cases involving state government dismissals, governor's report challenges, and federal-state disputes.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 6,
    title: "Arnesh Kumar v. State of Bihar",
    citation: "(2014) 8 SCC 273",
    year: 2014,
    bench: "2-Judge Bench",
    category: "criminal",
    tags: ["Criminal Law", "Arrest", "Bail", "Section 498A"],
    principle: "Police cannot arrest automatically in all cases under Section 498A IPC or Section 4 DPOA. Magistrates must apply mind before authorising arrest or detention.",
    holding: "Detailed guidelines issued for arrest in offences punishable with less than 7 years imprisonment. Checklist mandatory before arrest.",
    applicability: "Binding on all criminal courts in India. Magistrates must follow checklist before remand. Applied in bail applications and habeas corpus petitions.",
    approved: true,
    area: "Criminal Law",
  },
  {
    id: 7,
    title: "Lalita Kumari v. Government of U.P.",
    citation: "(2014) 2 SCC 1",
    year: 2014,
    bench: "5-Judge Constitution Bench",
    category: "criminal",
    tags: ["Criminal Law", "FIR", "CrPC Section 154"],
    principle: "Registration of FIR is mandatory if a cognizable offence is disclosed. Police have no discretion to conduct preliminary inquiry except in specific exceptional categories.",
    holding: "Section 154 CrPC mandates registration of FIR immediately upon receipt of information disclosing a cognizable offence.",
    applicability: "Binding on all criminal courts. Applied in writ petitions seeking registration of FIR and habeas corpus matters.",
    approved: true,
    area: "Criminal Law",
  },
  {
    id: 8,
    title: "Shayara Bano v. Union of India",
    citation: "(2017) 9 SCC 1",
    year: 2017,
    bench: "5-Judge Constitution Bench",
    category: "family",
    tags: ["Family Law", "Constitutional", "Muslim Personal Law"],
    principle: "Triple Talaq (instantaneous talaq-e-biddat) is unconstitutional as it is manifestly arbitrary and violates Article 14.",
    holding: "The practice of talaq-e-biddat is set aside as being violative of Article 14. It is manifestly arbitrary in the sense that it is capricious and irrational.",
    applicability: "Binding on all family courts and High Courts dealing with Muslim personal law matrimonial matters.",
    approved: true,
    area: "Family Law",
  },
  {
    id: 9,
    title: "Justice K.S. Puttaswamy v. Union of India",
    citation: "(2017) 10 SCC 1",
    year: 2017,
    bench: "9-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Privacy", "Fundamental Rights"],
    principle: "Right to Privacy is a fundamental right under Articles 14, 19 and 21 of the Constitution. It protects individual autonomy, dignity, and freedom of choice.",
    holding: "Privacy is a constitutionally protected right as an intrinsic part of life and personal liberty under Article 21.",
    applicability: "Binding on all courts. Applicable in data protection matters, surveillance challenges, Aadhaar cases, and all matters involving personal information.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 10,
    title: "Navtej Singh Johar v. Union of India",
    citation: "(2018) 10 SCC 1",
    year: 2018,
    bench: "5-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Section 377", "Equality"],
    principle: "Section 377 IPC, to the extent it criminalises consensual sexual conduct between adults of the same sex, is unconstitutional. Sexual orientation is a protected ground under Article 15.",
    holding: "Part of Section 377 IPC is unconstitutional as it violates Articles 14, 15, 19 and 21 of the Constitution.",
    applicability: "Binding on all courts. Applied in cases involving LGBTQ+ rights, anti-discrimination claims, and Article 21 liberty matters.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 11,
    title: "Olga Tellis v. Bombay Municipal Corporation",
    citation: "AIR 1986 SC 180 · (1985) 3 SCC 545",
    year: 1985,
    bench: "5-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Article 21", "Livelihood"],
    principle: "Right to livelihood is part of right to life under Article 21. Pavement dwellers cannot be evicted without due process of law.",
    holding: "The right to livelihood is borne out of the right to life. No person can live without means of living. Deprivation without just procedure violates Article 21.",
    applicability: "Applied in eviction matters, forced displacement cases, slum demolition PIL, and all cases involving right to livelihood.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 12,
    title: "Shreya Singhal v. Union of India",
    citation: "(2015) 5 SCC 1",
    year: 2015,
    bench: "2-Judge Bench",
    category: "constitutional",
    tags: ["Constitutional", "Freedom of Speech", "IT Act"],
    principle: "Section 66A of IT Act is unconstitutional as it vaguely restricts online speech and violates Article 19(1)(a). Only advocacy of incitement can be restricted.",
    holding: "Section 66A of the Information Technology Act 2000 is unconstitutional in its entirety being violative of Article 19(1)(a).",
    applicability: "Binding on all courts in cases involving online speech, freedom of expression challenges, and IT Act prosecutions.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 13,
    title: "M.C. Mehta v. Union of India (Absolute Liability)",
    citation: "AIR 1987 SC 1086 · (1987) 1 SCC 395",
    year: 1987,
    bench: "5-Judge Bench",
    category: "environmental",
    tags: ["Environment", "Absolute Liability", "Tort"],
    principle: "Enterprises engaged in hazardous activity are absolutely liable to compensate for harm caused. No exception of Act of God or third party fault applies.",
    holding: "An enterprise engaged in hazardous or inherently dangerous industry owes an absolute and non-delegable duty to the community to ensure no harm results.",
    applicability: "Binding on all courts in environmental matters, industrial accident cases, and hazardous substance liability.",
    approved: true,
    area: "Environmental Law",
  },
  {
    id: 14,
    title: "Indra Sawhney v. Union of India",
    citation: "AIR 1993 SC 477 · (1992) Supp (3) SCC 217",
    year: 1992,
    bench: "9-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Reservation", "OBC", "Article 16"],
    principle: "OBC reservation up to 27% is valid. Total reservation cannot exceed 50% except in extraordinary circumstances. Creamy layer must be excluded.",
    holding: "Backward class of citizens in Article 16(4) can be identified on the basis of caste. 50% ceiling on reservations subject to exceptional situations.",
    applicability: "Binding on all courts. Applied in all reservation matters, OBC quota challenges, service law disputes involving reservations.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 15,
    title: "A.K. Kraipak v. Union of India",
    citation: "AIR 1970 SC 150",
    year: 1970,
    bench: "5-Judge Constitution Bench",
    category: "administrative",
    tags: ["Administrative Law", "Natural Justice", "Service Law"],
    principle: "The rules of natural justice must be applied in all quasi-judicial proceedings. Audi alteram partem is a mandatory requirement even where statute is silent.",
    holding: "The line of demarcation between a quasi-judicial and administrative function is thin. Natural justice principles apply to both.",
    applicability: "Binding on all courts in service matters, disciplinary proceedings, and all cases involving quasi-judicial decision-making by authorities.",
    approved: true,
    area: "Administrative Law",
  },
  {
    id: 16,
    title: "Nilabati Behera v. State of Orissa",
    citation: "(1993) 2 SCC 746",
    year: 1993,
    bench: "3-Judge Bench",
    category: "constitutional",
    tags: ["Constitutional", "Article 21", "Custodial Death", "Compensation"],
    principle: "Constitutional courts can award compensation for violation of fundamental rights under Article 21. Public law remedy is distinct from private law remedy.",
    holding: "Award of compensation for enforcement of fundamental rights is a distinct public law remedy. Not bound by limitations of private law.",
    applicability: "Applied by High Courts and Supreme Court in custodial death, torture, wrongful detention, and police brutality cases.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 17,
    title: "E.P. Royappa v. State of Tamil Nadu",
    citation: "(1974) 4 SCC 3",
    year: 1974,
    bench: "5-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Article 14", "Equality", "Arbitrariness"],
    principle: "Equality is a dynamic concept. Arbitrariness is the antithesis of equality. Article 14 strikes at arbitrariness in State action in all its manifestations.",
    holding: "Article 14 has a highly activist magnitude — it interdicts arbitrariness and ensures fairness and equality of treatment in all State actions.",
    applicability: "Binding on all courts. Applied universally in challenges to State action, administrative decisions, and legislative validity.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 18,
    title: "Joseph Shine v. Union of India",
    citation: "(2018) 2 SCC 189",
    year: 2018,
    bench: "5-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Gender Equality", "Article 14", "Article 15"],
    principle: "Section 497 IPC (Adultery) is unconstitutional as it treats a woman as property of her husband and violates Articles 14, 15 and 21.",
    holding: "Section 497 IPC is struck down as unconstitutional for violating Articles 14, 15, and 21 of the Constitution.",
    applicability: "Binding on all criminal courts. Applied when challenging any criminal prosecution for adultery and gender discrimination cases.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 19,
    title: "Waman Rao v. Union of India",
    citation: "AIR 1981 SC 271 · (1981) 2 SCC 362",
    year: 1981,
    bench: "5-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "9th Schedule", "Property Rights"],
    principle: "Laws placed under the 9th Schedule after April 24, 1973 (Kesavananda) are subject to judicial review if they violate the basic structure.",
    holding: "9th Schedule laws enacted after 24 April 1973 that abridge fundamental rights can be judicially reviewed on basic structure grounds.",
    applicability: "Applied in property rights cases involving land reforms, acquisition laws, and constitutional validity of legislation.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 20,
    title: "State of Punjab v. Gurdev Singh",
    citation: "AIR 1991 SC 2219 · (1991) 4 SCC 1",
    year: 1991,
    bench: "3-Judge Bench",
    category: "service",
    tags: ["Service Law", "Natural Justice", "Disciplinary Proceedings"],
    principle: "Principles of natural justice — audi alteram partem — must be followed in all service matters. No adverse order without opportunity of hearing.",
    holding: "An order imposing penalty on a government servant without affording him an opportunity of hearing is void ab initio.",
    applicability: "Binding on all service courts and High Courts in service matters. Applied in disciplinary proceedings, termination challenges, and dismissal orders.",
    approved: true,
    area: "Service Law",
  },
  {
    id: 21,
    title: "Dwarka Nath v. Income Tax Officer",
    citation: "AIR 1966 SC 81",
    year: 1966,
    bench: "3-Judge Bench",
    category: "constitutional",
    tags: ["Constitutional", "Article 226", "Writ Jurisdiction"],
    principle: "Article 226 confers wide power to High Courts to issue any direction, order or writ — not confined to prerogative writs known to English law.",
    holding: "The High Court has power to issue any direction, order or writ including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari.",
    applicability: "Applied in all writ petitions before High Courts. Foundational for the wide scope of writ jurisdiction under Article 226.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 22,
    title: "State of U.P. v. Mohd. Nooh",
    citation: "AIR 1958 SC 86",
    year: 1958,
    bench: "5-Judge Constitution Bench",
    category: "constitutional",
    tags: ["Constitutional", "Writ Jurisdiction", "Article 226"],
    principle: "High Court's power under Article 226 is wider than the old certiorari jurisdiction under English law. It can issue any appropriate writ.",
    holding: "The jurisdiction of the High Court to issue a writ of certiorari under Article 226 is wider and can be exercised in cases beyond the scope of English certiorari.",
    applicability: "Applied in all writ petitions. Establishes broad jurisdiction of High Courts under Article 226.",
    approved: true,
    area: "Constitutional Law",
  },
  {
    id: 23,
    title: "Wander Ltd. v. Antox India (Interim Injunction)",
    citation: "1990 Supp SCC 727",
    year: 1990,
    bench: "2-Judge Bench",
    category: "civil",
    tags: ["Civil Law", "Injunction", "Interim Relief"],
    principle: "Three-pronged test for interim injunction: (1) prima facie case, (2) balance of convenience, (3) irreparable harm if not granted.",
    holding: "Courts granting interlocutory injunctions must be satisfied of prima facie case, balance of convenience favouring the applicant, and irreparable injury.",
    applicability: "Binding on all civil courts. Applied in every interim injunction application before district courts and High Courts.",
    approved: true,
    area: "Civil Law",
  },
  {
    id: 24,
    title: "Om Kumar v. Union of India",
    citation: "(2001) 2 SCC 386",
    year: 2001,
    bench: "2-Judge Bench",
    category: "administrative",
    tags: ["Administrative Law", "Proportionality", "Article 14"],
    principle: "Doctrine of proportionality — the punishment must be proportionate to the misconduct. Courts can interfere if penalty is grossly disproportionate.",
    holding: "The doctrine of proportionality requires that the measure adopted must be proportionate to the object sought to be achieved.",
    applicability: "Applied by High Courts in service matters, disciplinary proceedings, and administrative actions challenged under Article 226.",
    approved: true,
    area: "Administrative Law",
  },
  {
    id: 25,
    title: "Union of India v. Association for Democratic Reforms",
    citation: "(2002) 5 SCC 294",
    year: 2002,
    bench: "3-Judge Bench",
    category: "constitutional",
    tags: ["Constitutional", "Right to Information", "Elections"],
    principle: "Voters have a fundamental right to know the antecedents, assets, and criminal record of candidates contesting elections.",
    holding: "The right to get information in democracy is recognized throughout and it is a natural right flowing from Article 19(1)(a).",
    applicability: "Applied in election petition matters and RTI cases. Considered by High Courts in electoral disputes.",
    approved: true,
    area: "Constitutional Law",
  },
]

export const CATEGORIES = ["All", "Constitutional Law", "Criminal Law", "Civil Law", "Family Law", "Environmental Law", "Administrative Law", "Service Law"]

export const DOCUMENT_CATEGORIES = {
  SC: [
    {
      name: "Writ Jurisdiction",
      provision: "Art. 32",
      icon: "⚖",
      sub: ["Writ Petition (Civil)", "Writ Petition (Criminal)", "Habeas Corpus", "Mandamus", "Certiorari", "Prohibition", "Quo Warranto", "PIL — Environment", "PIL — Human Rights"],
    },
    {
      name: "Appellate Jurisdiction",
      provision: "Art. 136",
      icon: "📋",
      sub: ["Special Leave Petition (Civil)", "Special Leave Petition (Criminal)", "Appeal by Certificate (Art.132)", "Appeal by Certificate (Art.133)", "Transfer Petition"],
    },
    {
      name: "Review & Curative",
      provision: "Art. 137",
      icon: "🔍",
      sub: ["Review Petition (Civil)", "Review Petition (Criminal)", "Curative Petition"],
    },
    {
      name: "Original Jurisdiction",
      provision: "Art. 131",
      icon: "📜",
      sub: ["Inter-State Dispute", "Centre vs State", "Presidential Reference (Art. 143)"],
    },
    {
      name: "Contempt",
      provision: "Art. 129",
      icon: "📑",
      sub: ["Contempt Petition (Civil)", "Contempt Petition (Criminal)", "Suo Motu Contempt"],
    },
  ],
  HC: [
    {
      name: "Writ Jurisdiction",
      provision: "Art. 226",
      icon: "⚖",
      sub: ["Writ Petition (Civil)", "Writ Petition (Criminal)", "Habeas Corpus", "Mandamus", "Certiorari", "Prohibition", "Quo Warranto", "PIL"],
    },
    {
      name: "Civil Jurisdiction",
      provision: "CPC",
      icon: "🏛",
      sub: ["Regular Civil Suit", "Suit for Declaration", "Suit for Injunction", "Suit for Specific Performance", "Matrimonial Petition (Divorce)", "Letter Patent Appeal"],
    },
    {
      name: "Criminal Jurisdiction",
      provision: "CrPC",
      icon: "🔒",
      sub: ["Criminal Appeal", "Criminal Revision", "Anticipatory Bail (S.438)", "Regular Bail (S.439)", "Quashing of FIR (S.482)", "Quashing of Chargesheet"],
    },
    {
      name: "Appellate Jurisdiction",
      provision: "CPC/CrPC",
      icon: "📋",
      sub: ["First Appeal (CPC Order 41)", "Second Appeal (CPC S.100)", "Revision (CPC S.115)", "Revision (CrPC S.397)"],
    },
    {
      name: "Service & Labour",
      provision: "Art. 226",
      icon: "📜",
      sub: ["Service Matter Writ", "Writ against Termination", "Writ against Suspension", "Pay & Pension Dispute", "Labour Court Appeal"],
    },
    {
      name: "Revenue & Land",
      provision: "State Acts",
      icon: "🌿",
      sub: ["Land Acquisition Reference", "Revenue Court Appeal", "Tenancy Dispute", "Consolidation Appeal", "Mutation Challenge"],
    },
    {
      name: "Company & Tax",
      provision: "Various",
      icon: "💰",
      sub: ["Income Tax Appeal", "GST Appeal", "Company Petition", "Winding Up Petition", "Commercial Suit (>₹3L)"],
    },
    {
      name: "Contempt",
      provision: "Art. 215",
      icon: "⚡",
      sub: ["Civil Contempt Petition", "Criminal Contempt Petition", "Contempt of Subordinate Court"],
    },
  ],
}

export const HIGH_COURTS = [
  "Allahabad High Court", "Bombay High Court", "Calcutta High Court", "Delhi High Court",
  "Madras High Court", "Karnataka High Court", "Kerala High Court", "Gujarat High Court",
  "Rajasthan High Court", "Patna High Court", "Punjab & Haryana High Court",
  "Madhya Pradesh High Court", "Andhra Pradesh High Court", "Telangana High Court",
  "Himachal Pradesh High Court", "Jammu & Kashmir High Court", "Jharkhand High Court",
  "Chhattisgarh High Court", "Uttarakhand High Court", "Gauhati High Court",
  "Orissa High Court", "Sikkim High Court", "Tripura High Court", "Manipur High Court",
  "Meghalaya High Court",
]

export const STANDARD_CLAUSES = [
  { title: "Delay condonation clause", body: "That the present petition has been filed within limitation. However, if this Hon'ble Court finds any delay, the same may kindly be condoned in the interest of justice as the Petitioner has been pursuing the matter bonafide." },
  { title: "No alternative remedy clause", body: "That the Petitioner has no alternative efficacious remedy available under any other statute or law for the redressal of the grievance, and the present Writ Petition is the only remedy available to the Petitioner." },
  { title: "Locus standi affirmation", body: "That the Petitioner has locus standi to file the present petition as a person aggrieved by the impugned order and directly affected by the same." },
  { title: "Territorial jurisdiction clause", body: "That the cause of action, wholly or in part, has arisen within the territorial jurisdiction of this Hon'ble Court." },
  { title: "No previous petition clause", body: "That the Petitioner has not filed any similar petition before this Hon'ble Court or before the Hon'ble Supreme Court of India or before any other court or authority in respect of the subject matter of the present petition." },
  { title: "Res judicata exclusion", body: "That the subject matter of the present petition is not hit by the principle of res judicata as no previous adjudication on merits has taken place." },
  { title: "Urgency / mention clause", body: "That the matter is urgent in nature as the impugned order is being actively enforced and the Petitioner will suffer irreparable loss if the same is not stayed immediately." },
  { title: "Balance of convenience", body: "That the balance of convenience is entirely in favour of the Petitioner inasmuch as no prejudice shall be caused to the Respondents if interim relief is granted, whereas the Petitioner shall suffer irreparable loss if the same is not granted." },
  { title: "Clean hands affirmation", body: "That the Petitioner approaches this Hon'ble Court with clean hands, utmost good faith and without suppression of any material fact." },
  { title: "Liberty to file documents", body: "That the Petitioner craves leave to produce additional documents, affidavits, and evidence, if and when required and permitted by this Hon'ble Court." },
]
