// WritOnline — Supreme Court Precedents Database
// 150+ landmark judgements across all areas of Indian law

export interface Precedent {
  id: number
  title: string
  citation: string
  year: number
  bench: string
  benchStrength: number
  category: string
  area: string
  tags: string[]
  principle: string
  holding: string
  applicability: string
  approved: boolean
  overruledBy?: string
}

export const PRECEDENTS_DB: Precedent[] = [

  // ═══════════════════════════════════════════
  // CONSTITUTIONAL LAW
  // ═══════════════════════════════════════════

  {id:1,title:"Kesavananda Bharati v. State of Kerala",citation:"AIR 1973 SC 1461 · (1973) 4 SCC 225",year:1973,bench:"13-Judge Constitution Bench",benchStrength:13,category:"Constitutional Law",area:"Constitutional Law",tags:["Basic Structure","Fundamental Rights","Article 368","Parliament's Power"],principle:"Basic Structure Doctrine — Parliament cannot amend the Constitution so as to destroy its basic structure including judicial review, rule of law, separation of powers, and fundamental rights.",holding:"The power of Parliament under Article 368 does not include power to abrogate or emasculate the basic elements or fundamental features of the Constitution.",applicability:"Binding on all courts in India. Applied in all cases involving constitutional amendments, judicial review of legislative action, and fundamental rights challenges. High Courts must follow while examining state legislation.",approved:true},

  {id:2,title:"Maneka Gandhi v. Union of India",citation:"AIR 1978 SC 597 · (1978) 1 SCC 248",year:1978,bench:"7-Judge Constitution Bench",benchStrength:7,category:"Constitutional Law",area:"Constitutional Law",tags:["Article 21","Personal Liberty","Natural Justice","Due Process","Articles 14 19 21"],principle:"Article 21 — procedure established by law must be just, fair, and reasonable. Articles 14, 19 and 21 are not mutually exclusive water-tight compartments.",holding:"The expression 'procedure established by law' in Article 21 must be right, just, fair and not arbitrary, fanciful or oppressive.",applicability:"Binding on all courts. Fundamental in any case involving deprivation of life or personal liberty. Expanded interpretation applies across criminal, civil, administrative and public law matters.",approved:true},

  {id:3,title:"S.R. Bommai v. Union of India",citation:"AIR 1994 SC 1918 · (1994) 3 SCC 1",year:1994,bench:"9-Judge Constitution Bench",benchStrength:9,category:"Constitutional Law",area:"Constitutional Law",tags:["Article 356","Federalism","President's Rule","Secularism","Basic Structure"],principle:"Presidential Proclamation under Article 356 is subject to judicial review. Secularism and federalism are part of the basic structure of the Constitution.",holding:"Imposition of President's Rule under Article 356 is subject to judicial review. The majority in the state assembly must be tested on the floor of the House.",applicability:"Binding on High Courts in all cases involving state government dismissals, governor's report challenges, and federal-state disputes.",approved:true},

  {id:4,title:"Minerva Mills Ltd. v. Union of India",citation:"AIR 1980 SC 1789 · (1980) 3 SCC 625",year:1980,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["Basic Structure","Article 31C","Directive Principles","Judicial Review","42nd Amendment"],principle:"The power to amend the Constitution cannot be used to destroy the power of judicial review. The balance between Part III and Part IV is part of the basic structure.",holding:"Section 4 of the 42nd Amendment Act giving absolute primacy to Directive Principles over Fundamental Rights is unconstitutional as it destroys the basic structure.",applicability:"Applied in all cases involving conflict between Fundamental Rights and Directive Principles, and all constitutional amendment challenges.",approved:true},

  {id:5,title:"Indra Sawhney v. Union of India",citation:"AIR 1993 SC 477 · (1992) Supp (3) SCC 217",year:1992,bench:"9-Judge Constitution Bench",benchStrength:9,category:"Constitutional Law",area:"Constitutional Law",tags:["Reservation","OBC","Article 16","Creamy Layer","50% Ceiling","Mandal Commission"],principle:"OBC reservation up to 27% is valid. Total reservation cannot exceed 50% except in extraordinary circumstances. Creamy layer must be excluded from OBC benefits.",holding:"Backward class of citizens in Article 16(4) can be identified on caste basis. 50% ceiling on reservations. Separate reservation for economically backward among forward classes not permissible.",applicability:"Binding on all courts. Applied in all reservation matters, OBC quota challenges, service law disputes involving reservations.",approved:true},

  {id:6,title:"E.P. Royappa v. State of Tamil Nadu",citation:"(1974) 4 SCC 3",year:1974,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["Article 14","Equality","Arbitrariness","State Action","New Dimension"],principle:"Equality is a dynamic concept. Arbitrariness is the antithesis of equality. Article 14 strikes at arbitrariness in State action in all its manifestations.",holding:"Article 14 has a highly activist magnitude — it interdicts arbitrariness and ensures fairness and equality of treatment in all State actions.",applicability:"Binding on all courts. Applied universally in challenges to State action, administrative decisions, and legislative validity.",approved:true},

  {id:7,title:"Olga Tellis v. Bombay Municipal Corporation",citation:"AIR 1986 SC 180 · (1985) 3 SCC 545",year:1985,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["Article 21","Right to Livelihood","Eviction","Pavement Dwellers","Due Process"],principle:"Right to livelihood is part of right to life under Article 21. Pavement dwellers cannot be evicted without due process of law and opportunity of hearing.",holding:"The right to livelihood is borne out of the right to life, as no person can live without means of living. Deprivation without just procedure violates Article 21.",applicability:"Applied in eviction matters, forced displacement cases, slum demolition PIL, and all cases involving right to livelihood.",approved:true},

  {id:8,title:"Vishaka v. State of Rajasthan",citation:"AIR 1997 SC 3011 · (1997) 6 SCC 241",year:1997,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["Sexual Harassment","Workplace","Women Rights","Article 14","POSH"],principle:"Sexual harassment at workplace violates Articles 14, 19 and 21. Every employer must have a Sexual Harassment Committee and a detailed redressal mechanism.",holding:"Vishaka Guidelines laid down as binding law until legislative enactment. Superseded by POSH Act 2013.",applicability:"Binding on all courts and employers. High Courts apply while examining POSH Act compliance and workplace harassment matters.",approved:true},

  {id:9,title:"Justice K.S. Puttaswamy v. Union of India",citation:"(2017) 10 SCC 1",year:2017,bench:"9-Judge Constitution Bench",benchStrength:9,category:"Constitutional Law",area:"Constitutional Law",tags:["Privacy","Fundamental Rights","Aadhaar","Data Protection","Article 21","Dignity"],principle:"Right to Privacy is a fundamental right under Articles 14, 19 and 21. It protects individual autonomy, dignity, and freedom of choice.",holding:"Privacy is a constitutionally protected right as an intrinsic part of life and personal liberty under Article 21.",applicability:"Binding on all courts. Applicable in data protection, surveillance challenges, Aadhaar cases, and all matters involving personal information.",approved:true},

  {id:10,title:"Navtej Singh Johar v. Union of India",citation:"(2018) 10 SCC 1",year:2018,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["Section 377","LGBTQ+","Article 14","Article 15","Sexual Orientation","Article 21"],principle:"Section 377 IPC, to the extent it criminalises consensual sexual conduct between adults of the same sex, is unconstitutional. Sexual orientation is protected under Article 15.",holding:"Part of Section 377 IPC is unconstitutional as it violates Articles 14, 15, 19 and 21 of the Constitution.",applicability:"Binding on all courts. Applied in LGBTQ+ rights, anti-discrimination claims, and Article 21 liberty matters.",approved:true},

  {id:11,title:"Joseph Shine v. Union of India",citation:"(2018) 2 SCC 189",year:2018,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["Adultery","Section 497 IPC","Gender Equality","Article 14","Article 15","Struck Down"],principle:"Section 497 IPC (Adultery) is unconstitutional as it treats a woman as property of her husband and violates Articles 14, 15 and 21.",holding:"Section 497 IPC is struck down as unconstitutional for violating Articles 14, 15, and 21 of the Constitution.",applicability:"Binding on all criminal courts. Applied in gender discrimination cases and adultery prosecutions.",approved:true},

  {id:12,title:"Shreya Singhal v. Union of India",citation:"(2015) 5 SCC 1",year:2015,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Freedom of Speech","IT Act","Section 66A","Article 19","Online Speech","Struck Down"],principle:"Section 66A of IT Act is unconstitutional as it vaguely restricts online speech and violates Article 19(1)(a).",holding:"Section 66A of the Information Technology Act 2000 is unconstitutional in its entirety being violative of Article 19(1)(a).",applicability:"Binding on all courts in cases involving online speech, freedom of expression challenges, and IT Act prosecutions.",approved:true},

  {id:13,title:"Shayara Bano v. Union of India",citation:"(2017) 9 SCC 1",year:2017,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Family Law",tags:["Triple Talaq","Muslim Personal Law","Article 14","Talaq-e-Biddat","Manifestly Arbitrary"],principle:"Triple Talaq (instantaneous talaq-e-biddat) is unconstitutional as it is manifestly arbitrary and violates Article 14.",holding:"The practice of talaq-e-biddat is set aside as being violative of Article 14. It is manifestly arbitrary — capricious and irrational.",applicability:"Binding on all family courts dealing with Muslim personal law matrimonial matters.",approved:true},

  {id:14,title:"Waman Rao v. Union of India",citation:"AIR 1981 SC 271 · (1981) 2 SCC 362",year:1981,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["9th Schedule","Property Rights","Judicial Review","Basic Structure","Post-1973"],principle:"Laws placed under the 9th Schedule after April 24, 1973 (Kesavananda) are subject to judicial review if they violate the basic structure.",holding:"9th Schedule laws enacted after 24 April 1973 that abridge fundamental rights can be judicially reviewed on basic structure grounds.",applicability:"Applied in property rights cases involving land reforms, acquisition laws, and constitutional validity of legislation.",approved:true},

  {id:15,title:"National Legal Services Authority v. Union of India",citation:"(2014) 5 SCC 438",year:2014,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Transgender Rights","Third Gender","Article 14","Article 21","Self-Identification","Identity"],principle:"Transgender persons have the right to self-identify their gender under Articles 14, 15, 19 and 21. They constitute the third gender.",holding:"Recognition of the right of transgender persons to decide their self-identified gender. Directions issued to government for their welfare.",applicability:"Binding on all authorities. Applied in cases involving transgender rights and gender identity.",approved:true},

  {id:16,title:"People's Union for Democratic Rights v. Union of India",citation:"AIR 1982 SC 1473 · (1982) 3 SCC 235",year:1982,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["PIL","Article 32","Locus Standi","Public Interest Litigation","Access to Justice"],principle:"PIL can be filed by any person or public spirited organisation on behalf of those who cannot access courts. Liberalised locus standi.",holding:"Any member of the public can maintain an action by way of PIL when there is a violation of fundamental rights of persons who cannot approach the Court.",applicability:"Foundational for all PIL cases. Applied in all cases where access to justice for marginalised sections is involved.",approved:true},

  {id:17,title:"Union of India v. Association for Democratic Reforms",citation:"(2002) 5 SCC 294",year:2002,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["Right to Information","Elections","Candidates","Article 19","Voter Rights"],principle:"Voters have a fundamental right to know the antecedents, assets, and criminal record of candidates contesting elections.",holding:"The right to get information in democracy is recognised throughout and it is a natural right flowing from Article 19(1)(a).",applicability:"Applied in election petition matters and RTI cases. Considered by High Courts in electoral disputes.",approved:true},

  {id:18,title:"Nilabati Behera v. State of Orissa",citation:"(1993) 2 SCC 746",year:1993,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["Custodial Death","Article 21","Compensation","Public Law Remedy","Constitutional Tort"],principle:"Constitutional courts can award compensation for violation of fundamental rights under Article 21. Public law remedy is distinct from private law remedy.",holding:"Award of compensation for enforcement of fundamental rights is a distinct public law remedy. Not bound by limitations of private law.",applicability:"Applied in custodial death, torture, wrongful detention, and police brutality cases.",approved:true},

  {id:19,title:"D.K. Basu v. State of West Bengal",citation:"AIR 1997 SC 610 · (1997) 1 SCC 416",year:1997,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Criminal Law",tags:["Arrest Guidelines","Custody","Article 21","Police Brutality","11 Guidelines"],principle:"Comprehensive guidelines for arrest and detention to prevent custodial violence and protect the rights of arrested persons.",holding:"Laid down 11 mandatory requirements to be followed in all cases of arrest and detention. Non-compliance may render the concerned official liable for contempt.",applicability:"Binding on all police authorities and magistrates. Applied in all cases of alleged illegal arrest or custodial violence.",approved:true},

  {id:20,title:"Anuj Garg v. Hotel Association of India",citation:"(2008) 3 SCC 1",year:2008,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Article 15","Gender Discrimination","Women Employment","Paternalistic Legislation","Article 19"],principle:"Protective legislation for women must not be paternalistic or reinforce gender stereotypes. A law protecting women by restricting employment is unconstitutional.",holding:"Section 30 of Punjab Excise Act prohibiting employment of women in licensed premises is unconstitutional — violates Articles 14, 15 and 19.",applicability:"Applied in cases challenging gender-based employment restrictions and discriminatory protective legislation.",approved:true},

  {id:21,title:"Hussainara Khatoon v. State of Bihar",citation:"(1979) 3 SCC 1",year:1979,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["Speedy Trial","Article 21","Undertrial Prisoners","Right to Fair Trial","Personal Liberty"],principle:"The right to speedy trial is a component of the right to life and personal liberty under Article 21.",holding:"An accused has a fundamental right to speedy trial. Undertrials cannot be kept in jail for period longer than maximum sentence for the offence.",applicability:"Applied in all cases involving inordinate delay in trial and rights of undertrial prisoners.",approved:true},

  {id:22,title:"Common Cause v. Union of India (Passive Euthanasia)",citation:"(2018) 5 SCC 1",year:2018,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["Right to Die","Passive Euthanasia","Living Will","Article 21","Dignity","Advance Directive"],principle:"The right to die with dignity is a fundamental right under Article 21. Passive euthanasia and advance medical directives are recognised.",holding:"Passive euthanasia is allowed. An individual has the right to execute an 'advance directive' refusing medical treatment in a terminal condition.",applicability:"Applied in cases involving right to die, passive euthanasia, and advance medical directives.",approved:true},

  {id:23,title:"Parmanand Katara v. Union of India",citation:"(1989) 4 SCC 286",year:1989,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Medical Emergency","Article 21","Emergency Treatment","Hospitals","No Refusal"],principle:"Every doctor whether government or private has a duty to treat accident victims in an emergency without waiting for medico-legal formalities.",holding:"Article 21 imposes an obligation on every medical professional to treat victims of accidents. No hospital or doctor can refuse emergency treatment.",applicability:"Applied in cases involving denial of emergency medical treatment and liability of hospitals.",approved:true},

  {id:24,title:"Sunil Batra v. Delhi Administration",citation:"(1978) 4 SCC 494",year:1978,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Prison Law",area:"Constitutional Law",tags:["Prison Reforms","Article 21","Solitary Confinement","Prisoner Rights","Habeas Corpus"],principle:"Prisoners do not shed their fundamental rights at the prison gate. Article 21 protection extends to prisoners.",holding:"Prisoners retain all fundamental rights except those forfeited by the process of incarceration. Solitary confinement is permissible only in exceptional cases.",applicability:"Applied in all cases involving prisoner rights, prison conditions, and habeas corpus petitions.",approved:true},

  {id:25,title:"Anuradha Bhasin v. Union of India",citation:"(2020) 3 SCC 637",year:2020,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["Internet Shutdown","Article 19","Freedom of Press","Kashmir","Proportionality","Review Committee"],principle:"The right to access the Internet is part of the freedom of speech and expression under Article 19(1)(a). Internet shutdowns must be proportionate.",holding:"Indefinite internet shutdowns are unconstitutional. All orders imposing internet shutdowns must be reviewed by a Review Committee.",applicability:"Applied in cases involving internet shutdowns, freedom of expression, and proportionality of restrictions.",approved:true},

  {id:26,title:"State of West Bengal v. Anwar Ali Sarkar",citation:"AIR 1952 SC 75",year:1952,bench:"7-Judge Constitution Bench",benchStrength:7,category:"Constitutional Law",area:"Constitutional Law",tags:["Article 14","Reasonable Classification","Intelligible Differentia","Nexus Test","Equality"],principle:"Reasonable classification for purposes of Article 14 must satisfy two conditions: intelligible differentia and nexus with the object of legislation.",holding:"Article 14 forbids class legislation but permits reasonable classification based on intelligible differentia with rational nexus to the object.",applicability:"Foundational test for Article 14 challenge to classification in legislation. Applied in all equality challenges.",approved:true},

  {id:27,title:"Romesh Thappar v. State of Madras",citation:"AIR 1950 SC 124",year:1950,bench:"6-Judge Bench",benchStrength:6,category:"Constitutional Law",area:"Constitutional Law",tags:["Freedom of Press","Article 19(1)(a)","Article 19(2)","Reasonable Restrictions","Press Freedom"],principle:"Freedom of the press is included in the freedom of speech and expression under Article 19(1)(a). Restrictions on press must fall within Article 19(2).",holding:"Section 9(1-A) of Madras Maintenance of Public Order Act imposing restriction on press was struck down as unconstitutional.",applicability:"Foundational case for press freedom. Applied in all cases involving restrictions on media and publication.",approved:true},

  {id:28,title:"Bennett Coleman & Co. v. Union of India",citation:"(1972) 2 SCC 788",year:1972,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Constitutional Law",area:"Constitutional Law",tags:["Newsprint Policy","Press Freedom","Article 19(1)(a)","Circulation","Media Freedom"],principle:"Any law that directly infringes the freedom of the press will be struck down. Restrictions on newsprint allocation amount to restriction on press freedom.",holding:"The Newsprint Control Order controlling newsprint allocation is an unconstitutional restriction on freedom of the press.",applicability:"Applied in cases involving government regulation of media, newsprint policy, and press freedoms.",approved:true},

  {id:29,title:"Tehseen Poonawalla v. Union of India",citation:"(2018) 9 SCC 501",year:2018,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["Mob Lynching","Rule of Law","Article 21","Vigilantism","State Duty","Communal Violence"],principle:"Mob lynching and vigilantism are antithetical to the rule of law. The State has a constitutional duty to prevent such acts.",holding:"Comprehensive directions issued to prevent mob lynching and vigilante violence. States must enact laws against lynching.",applicability:"Applied in cases involving mob violence, hate crimes, and State accountability for communal violence.",approved:true},

  {id:30,title:"L. Chandra Kumar v. Union of India",citation:"(1997) 3 SCC 261",year:1997,bench:"7-Judge Constitution Bench",benchStrength:7,category:"Constitutional Law",area:"Constitutional Law",tags:["Tribunals","Article 226","Article 227","Judicial Review","Basic Structure","High Court Jurisdiction"],principle:"The jurisdiction of High Courts under Articles 226 and 227 cannot be ousted by establishing tribunals. Judicial review is part of the basic structure.",holding:"The power of judicial review vested in High Courts under Articles 226 and 227 is part of the basic structure and cannot be excluded even by constitutional amendment.",applicability:"Applied in all cases challenging the jurisdiction of tribunals and attempts to exclude High Court jurisdiction.",approved:true},

  // ═══════════════════════════════════════════
  // CRIMINAL LAW
  // ═══════════════════════════════════════════

  {id:31,title:"Bachan Singh v. State of Punjab",citation:"AIR 1980 SC 898 · (1980) 2 SCC 684",year:1980,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Criminal Law",area:"Criminal Law",tags:["Death Penalty","Rarest of Rare","Sentencing","Section 302 IPC","Capital Punishment"],principle:"Death penalty is constitutionally valid but must be awarded only in the 'rarest of rare' cases after weighing aggravating and mitigating circumstances.",holding:"Section 302 IPC providing death penalty is not violative of Articles 19 and 21. The rarest of rare doctrine governs sentencing discretion.",applicability:"Binding on all criminal courts. Applied mandatorily in all capital punishment sentencing. HC must apply rarest of rare test before confirming death sentence.",approved:true},

  {id:32,title:"Machhi Singh v. State of Punjab",citation:"(1983) 3 SCC 470",year:1983,bench:"3-Judge Bench",benchStrength:3,category:"Criminal Law",area:"Criminal Law",tags:["Death Penalty","Rarest of Rare","Aggravating Circumstances","Mitigating Circumstances","Five Categories"],principle:"Elaborated the 'rarest of rare' test by laying down specific categories of cases where death penalty may be imposed.",holding:"Five categories of cases where death sentence may be warranted: manner of commission, motive, nature, magnitude of crime, and personality of victim.",applicability:"Binding on all criminal courts. Applied in conjunction with Bachan Singh in all capital punishment cases.",approved:true},

  {id:33,title:"Arnesh Kumar v. State of Bihar",citation:"(2014) 8 SCC 273",year:2014,bench:"2-Judge Bench",benchStrength:2,category:"Criminal Law",area:"Criminal Law",tags:["Arrest","Section 498A IPC","CrPC Section 41","Bail","Checklist","No Automatic Arrest"],principle:"Police cannot arrest automatically in all cases under Section 498A IPC. Magistrates must apply mind before authorising arrest or detention.",holding:"Detailed guidelines issued for arrest in offences punishable with less than 7 years imprisonment. Checklist mandatory before arrest.",applicability:"Binding on all criminal courts. Applied in bail applications and habeas corpus petitions challenging illegal arrest.",approved:true},

  {id:34,title:"Lalita Kumari v. Government of U.P.",citation:"(2014) 2 SCC 1",year:2014,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Criminal Law",area:"Criminal Law",tags:["FIR","CrPC Section 154","Cognizable Offence","Mandatory Registration","No Preliminary Inquiry"],principle:"Registration of FIR is mandatory if a cognizable offence is disclosed. Police have no discretion to conduct preliminary inquiry in most cases.",holding:"Section 154 CrPC mandates registration of FIR immediately upon receipt of information disclosing a cognizable offence.",applicability:"Binding on all criminal courts. Applied in writ petitions seeking registration of FIR and habeas corpus matters.",approved:true},

  {id:35,title:"State of Rajasthan v. Balchand",citation:"AIR 1977 SC 2447 · (1977) 4 SCC 308",year:1977,bench:"2-Judge Bench",benchStrength:2,category:"Criminal Law",area:"Criminal Law",tags:["Bail","Default Bail","Personal Liberty","Article 21","Bail is Rule Jail Exception"],principle:"Bail is the rule and jail is the exception. The normal rule is bail unless there are strong reasons to refuse.",holding:"The basic rule is bail, not jail, and it is only when stringent grounds exist for refusing bail that the court should refuse it.",applicability:"Applied in all bail applications across all courts in India.",approved:true},

  {id:36,title:"Sanjay Chandra v. CBI",citation:"(2012) 1 SCC 40",year:2012,bench:"2-Judge Bench",benchStrength:2,category:"Criminal Law",area:"Criminal Law",tags:["Bail","Economic Offences","2G Scam","Personal Liberty","Commercial Crime"],principle:"Even in economic offence cases, bail cannot be refused mechanically. Personal liberty is of utmost importance.",holding:"The purpose of bail is not punitive but to ensure presence of the accused at trial. Economic gravity alone is not sufficient to refuse bail.",applicability:"Applied in bail applications in economic offence cases, PMLA cases, and white-collar crime matters.",approved:true},

  {id:37,title:"D.K. Basu v. State of West Bengal (Arrest Guidelines)",citation:"AIR 1997 SC 610 · (1997) 1 SCC 416",year:1997,bench:"2-Judge Bench",benchStrength:2,category:"Criminal Law",area:"Criminal Law",tags:["Arrest","Custody","Article 21","Police Guidelines","Custodial Violence","11 Requirements"],principle:"Comprehensive guidelines for arrest and detention to prevent custodial violence. Non-compliance is contempt of court.",holding:"Laid down 11 mandatory requirements to be followed in all cases of arrest and detention.",applicability:"Binding on all police authorities and magistrates in India in all arrest and detention matters.",approved:true},

  {id:38,title:"Selvi v. State of Karnataka",citation:"(2010) 7 SCC 263",year:2010,bench:"3-Judge Bench",benchStrength:3,category:"Criminal Law",area:"Criminal Law",tags:["Narco Analysis","Brain Mapping","Polygraph","Article 20(3)","Self-Incrimination","Scientific Tests"],principle:"Involuntary administration of scientific tests like narco analysis, brain mapping and polygraph violates Article 20(3) right against self-incrimination.",holding:"Forcible administration of narco analysis, brain mapping and polygraph tests violates right against self-incrimination under Article 20(3).",applicability:"Applied in all cases involving attempts to compel accused persons to undergo scientific tests.",approved:true},

  {id:39,title:"State of Punjab v. Gurmit Singh",citation:"(1996) 2 SCC 384",year:1996,bench:"3-Judge Bench",benchStrength:3,category:"Criminal Law",area:"Criminal Law",tags:["Rape","Section 376 IPC","Victim Testimony","No Corroboration Required","Sexual Assault"],principle:"In rape cases, conviction can be based on the sole testimony of the victim without corroboration, if her testimony is credible and reliable.",holding:"The testimony of a victim of sexual assault is entitled to great weight. Corroboration is not a prerequisite for conviction in rape cases.",applicability:"Binding on all criminal courts in sexual assault cases. Applied in evaluating victim testimony.",approved:true},

  {id:40,title:"Zahira Habibulla Sheikh v. State of Gujarat",citation:"(2004) 4 SCC 158",year:2004,bench:"3-Judge Bench",benchStrength:3,category:"Criminal Law",area:"Criminal Law",tags:["Fair Trial","Witness Protection","Best Bakery Case","Retrial","Witness Intimidation"],principle:"The right to a fair trial is a fundamental right under Article 21. The court has power to transfer cases to ensure fair trial.",holding:"Retrial ordered in Best Bakery case due to large-scale witness intimidation and failure of justice.",applicability:"Applied in cases involving witness intimidation, transfer petitions, and fair trial challenges.",approved:true},

  {id:41,title:"Vijay Madanlal Choudhary v. Union of India",citation:"(2022) 10 SCC 1",year:2022,bench:"3-Judge Bench",benchStrength:3,category:"Criminal Law",area:"Criminal Law",tags:["PMLA","Money Laundering","ED","Bail","Section 45 PMLA","Twin Conditions"],principle:"Section 45 of PMLA imposes twin conditions for bail in money laundering cases, which are constitutionally valid.",holding:"The stringent conditions for bail under PMLA are valid. The presumption of guilt and reverse burden of proof in PMLA are constitutionally permissible.",applicability:"Applied in all PMLA cases involving bail applications and challenges to ED proceedings.",approved:true},

  {id:42,title:"State of Punjab v. Baldev Singh",citation:"(1999) 6 SCC 172",year:1999,bench:"3-Judge Bench",benchStrength:3,category:"Criminal Law",area:"Criminal Law",tags:["NDPS Act","Section 50","Search","Empowered Officer","Mandatory Requirement","Admissibility"],principle:"The requirement of informing the accused of their right to be searched before a Magistrate under Section 50 NDPS Act is mandatory.",holding:"Non-compliance with Section 50 NDPS Act makes the search illegal and the recovered contraband inadmissible as evidence.",applicability:"Applied in all NDPS cases involving challenge to search and seizure procedures.",approved:true},

  {id:43,title:"P. Ramachandra Rao v. State of Karnataka",citation:"(2002) 4 SCC 578",year:2002,bench:"7-Judge Constitution Bench",benchStrength:7,category:"Criminal Law",area:"Criminal Law",tags:["Speedy Trial","Delay","Article 21","Criminal Trial","No Fixed Period"],principle:"Prolonged delay in trial violates Article 21 right to speedy trial. Courts may discharge or acquit accused if delay is inordinate and unjustified.",holding:"No period of delay should be fixed as the outer limit for conclusion of all criminal cases. Each case must be decided on its facts.",applicability:"Applied in cases involving inordinate delay in criminal trials and motions for discharge due to delay.",approved:true},

  {id:44,title:"Mukesh v. State (NCT of Delhi) — Nirbhaya Case",citation:"(2017) 6 SCC 1",year:2017,bench:"3-Judge Bench",benchStrength:3,category:"Criminal Law",area:"Criminal Law",tags:["Rape","Gang Rape","Death Penalty","Rarest of Rare","Section 376 IPC","December 16"],principle:"Gang rape of a victim resulting in death is among the rarest of rare cases warranting death penalty.",holding:"The convicts in the Delhi gang rape case were sentenced to death, upholding the Sessions Court and High Court orders.",applicability:"Applied in all gang rape and murder cases involving consideration of death penalty.",approved:true},

  {id:45,title:"Asha Ranjan v. State of Bihar",citation:"(2017) 4 SCC 397",year:2017,bench:"2-Judge Bench",benchStrength:2,category:"Criminal Law",area:"Criminal Law",tags:["Victim Rights","Criminal Trial","POCSO","Bail Opposition","Victim Participation"],principle:"Victims of crime have rights in criminal proceedings including the right to oppose bail and transfer of case.",holding:"The victim of a crime has the right to participate in criminal proceedings and oppose bail of the accused.",applicability:"Applied in POCSO cases and other criminal cases involving victims' rights in proceedings.",approved:true},

  {id:46,title:"Paramvir Singh Saini v. Balia",citation:"(2021) 1 SCC 184",year:2021,bench:"2-Judge Bench",benchStrength:2,category:"Criminal Law",area:"Criminal Law",tags:["CCTV","Police Stations","Custodial Violence","Mandatory CCTV","Night Vision","D.K. Basu"],principle:"Installation of CCTV cameras in police stations and other custody facilities is mandatory to prevent custodial violence.",holding:"All States and Union Territories directed to install CCTV cameras with night-vision capability in police stations.",applicability:"Applied in cases involving custodial violence, police accountability, and implementation of D.K. Basu guidelines.",approved:true},

  {id:47,title:"Joginder Kumar v. State of U.P.",citation:"(1994) 4 SCC 260",year:1994,bench:"2-Judge Bench",benchStrength:2,category:"Criminal Law",area:"Criminal Law",tags:["Arrest","Article 21","CrPC","Police Power","Personal Liberty","No Automatic Arrest"],principle:"Arrest of a person in connection with investigation is not automatic. Police must justify arrest with reasonable grounds.",holding:"No arrest should be made without a reasonable complaint, credible information, or reasonable suspicion. The person arrested must be informed of grounds.",applicability:"Applied in cases involving illegal arrest and habeas corpus petitions challenging arrest.",approved:true},

  // ═══════════════════════════════════════════
  // CIVIL LAW
  // ═══════════════════════════════════════════

  {id:48,title:"Wander Ltd. v. Antox India Pvt. Ltd.",citation:"1990 Supp SCC 727",year:1990,bench:"2-Judge Bench",benchStrength:2,category:"Civil Law",area:"Civil Law",tags:["Injunction","Interim Relief","Prima Facie Case","Balance of Convenience","Irreparable Harm"],principle:"Three-pronged test for interim injunction: prima facie case, balance of convenience, irreparable harm.",holding:"Courts granting interlocutory injunctions must be satisfied of prima facie case, balance of convenience favouring applicant, and irreparable injury.",applicability:"Binding on all civil courts. Applied in every interim injunction application before district courts and High Courts.",approved:true},

  {id:49,title:"Dalpat Kumar v. Prahlad Singh",citation:"(1993) 1 SCC 719",year:1993,bench:"2-Judge Bench",benchStrength:2,category:"Civil Law",area:"Civil Law",tags:["Temporary Injunction","Order 39 CPC","Prima Facie","Status Quo","Three Conditions"],principle:"For grant of temporary injunction, the court must be satisfied that there is a prima facie case, balance of convenience is in favour of the applicant, and the applicant would suffer irreparable injury.",holding:"All three conditions must be satisfied cumulatively for grant of temporary injunction under Order 39 Rules 1 and 2.",applicability:"Applied in all civil courts in temporary injunction applications.",approved:true},

  {id:50,title:"Dorab Cawasji Warden v. Coomi Sorab Warden",citation:"(1990) 2 SCC 117",year:1990,bench:"2-Judge Bench",benchStrength:2,category:"Civil Law",area:"Civil Law",tags:["Mandatory Injunction","Interim","Prima Facie","High Threshold","Irreparable Harm"],principle:"An interim mandatory injunction can be granted only in cases of extreme hardship and when there is a clear case of immediate irreparable injury.",holding:"The court should be very slow to grant an interim mandatory injunction. Higher threshold than prohibitory injunction.",applicability:"Applied in all cases seeking interim mandatory injunctions in civil courts.",approved:true},

  {id:51,title:"Ramrameshwari Devi v. Nirmala Devi",citation:"(2011) 8 SCC 249",year:2011,bench:"2-Judge Bench",benchStrength:2,category:"Civil Law",area:"Civil Law",tags:["False Claims","Frivolous Litigation","Exemplary Costs","Abuse of Process","Realistic Costs"],principle:"Courts must impose exemplary costs on litigants who file frivolous, false, or vexatious litigation to discourage abuse of process.",holding:"Detailed guidelines issued for imposition of actual or realistic costs on parties who file frivolous litigation.",applicability:"Applied by High Courts and district courts in cases involving false claims and misuse of judicial process.",approved:true},

  {id:52,title:"A. Nawab John v. V.N. Subramaniyam",citation:"(2012) 7 SCC 738",year:2012,bench:"2-Judge Bench",benchStrength:2,category:"Civil Law",area:"Civil Law",tags:["Ex-Parte Decree","Setting Aside","Order 9 Rule 13 CPC","Sufficient Cause","Liberal Interpretation"],principle:"The expression 'sufficient cause' for setting aside ex-parte decree should be interpreted liberally to advance the cause of justice.",holding:"Courts should set aside ex-parte decrees if the party satisfies the court of sufficient cause for absence and has a meritorious defence.",applicability:"Applied in all applications to set aside ex-parte decrees under Order 9 Rule 13 CPC.",approved:true},

  {id:53,title:"Maria Margarida Sequeria Fernandes v. Erasmo Jack de Sequeria",citation:"(2012) 5 SCC 370",year:2012,bench:"2-Judge Bench",benchStrength:2,category:"Civil Law",area:"Civil Law",tags:["Possession","Property Dispute","Article 300A","Right to Property","Due Process"],principle:"A person in peaceful possession of property cannot be dispossessed except by due process of law.",holding:"Right to property, though not a fundamental right, is a constitutional right under Article 300A. No person can be deprived of it except by authority of law.",applicability:"Applied in all property possession disputes and cases involving forcible dispossession.",approved:true},

  {id:54,title:"Firm Srinivas Ram Kumar v. Mahabir Prasad",citation:"AIR 1951 SC 177",year:1951,bench:"7-Judge Constitution Bench",benchStrength:7,category:"Civil Law",area:"Civil Law",tags:["Res Judicata","Section 11 CPC","Final Decision","Same Parties","Finality"],principle:"The doctrine of res judicata prevents relitigation of issues that have been finally decided between the same parties by a competent court.",holding:"Section 11 CPC embodies the principle of res judicata. A final decision on merits by a competent court bars relitigation of the same matter.",applicability:"Applied universally in all civil proceedings to prevent abuse of process through relitigation.",approved:true},

  {id:55,title:"Ambalal Sarabhai Enterprises Ltd. v. Amrit Lal & Co.",citation:"(2001) 8 SCC 397",year:2001,bench:"2-Judge Bench",benchStrength:2,category:"Civil Law",area:"Civil Law",tags:["Adverse Possession","Limitation","Hostile Possession","Open Continuous","Article 65"],principle:"For adverse possession, the possession must be open, continuous, hostile, and to the knowledge of the true owner for the statutory period.",holding:"The claimant of adverse possession must establish actual possession, hostile claim, and continuity for the limitation period.",applicability:"Applied by all civil courts and High Courts in property and land possession disputes.",approved:true},

  // ═══════════════════════════════════════════
  // ADMINISTRATIVE LAW
  // ═══════════════════════════════════════════

  {id:56,title:"A.K. Kraipak v. Union of India",citation:"AIR 1970 SC 150",year:1970,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Administrative Law",area:"Administrative Law",tags:["Natural Justice","Quasi-Judicial","Audi Alteram Partem","Administrative Action","Bias"],principle:"Rules of natural justice must be applied in all quasi-judicial proceedings. Audi alteram partem is a mandatory requirement even where statute is silent.",holding:"The line between quasi-judicial and administrative function is thin. Natural justice applies to both in cases affecting rights.",applicability:"Binding on all courts in service matters, disciplinary proceedings, and quasi-judicial decisions by authorities.",approved:true},

  {id:57,title:"Om Kumar v. Union of India",citation:"(2001) 2 SCC 386",year:2001,bench:"2-Judge Bench",benchStrength:2,category:"Administrative Law",area:"Administrative Law",tags:["Proportionality","Disciplinary Action","Article 14","Judicial Review","Grossly Disproportionate"],principle:"Doctrine of proportionality — the punishment must be proportionate to the misconduct. Courts can interfere if penalty is grossly disproportionate.",holding:"The doctrine of proportionality requires that the measure adopted must be proportionate to the object sought to be achieved.",applicability:"Applied by High Courts in service matters, disciplinary proceedings, and administrative actions.",approved:true},

  {id:58,title:"Tata Cellular v. Union of India",citation:"(1994) 6 SCC 651",year:1994,bench:"3-Judge Bench",benchStrength:3,category:"Administrative Law",area:"Administrative Law",tags:["Judicial Review","Government Contracts","Wednesbury Unreasonableness","Tender","Limited Scope"],principle:"Courts should exercise judicial review of government contracts with restraint, interfering only when decision is mala fide, arbitrary, or irrational.",holding:"The scope of judicial review in contractual matters is limited to Wednesbury unreasonableness, procedural impropriety, and illegality.",applicability:"Applied in tender cases, government procurement matters, and judicial review of commercial decisions of the State.",approved:true},

  {id:59,title:"Shri Sitaram Sugar Co. Ltd. v. Union of India",citation:"AIR 1990 SC 1277 · (1990) 3 SCC 223",year:1990,bench:"3-Judge Bench",benchStrength:3,category:"Administrative Law",area:"Administrative Law",tags:["Promissory Estoppel","Government Policy","Legitimate Expectation","State Bound by Promise"],principle:"The doctrine of promissory estoppel applies against the government. The government cannot go back on a promise that induced action by a party.",holding:"Government is bound by its representations which induced parties to change their position. Doctrine of promissory estoppel applies to the State.",applicability:"Applied in cases involving government promises, incentives, and policy changes affecting reliance interests.",approved:true},

  {id:60,title:"Ajay Hasia v. Khalid Mujib Sehravardi",citation:"(1981) 1 SCC 722",year:1981,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Administrative Law",area:"Service Law",tags:["Article 12","State","Public Authority","Instrumentality of State","Government Company"],principle:"An entity is a 'State' under Article 12 if it is an instrumentality or agency of the government, even if not created by statute.",holding:"Laid down tests for determining whether a body is an instrumentality of the State under Article 12.",applicability:"Applied in all cases determining whether a body is amenable to writ jurisdiction under Article 226.",approved:true},

  // ═══════════════════════════════════════════
  // SERVICE LAW
  // ═══════════════════════════════════════════

  {id:61,title:"State of Punjab v. Gurdev Singh",citation:"AIR 1991 SC 2219 · (1991) 4 SCC 1",year:1991,bench:"3-Judge Bench",benchStrength:3,category:"Service Law",area:"Service Law",tags:["Natural Justice","Disciplinary Proceedings","Government Servant","Show Cause Notice","Void Order"],principle:"An order imposing penalty on a government servant without affording him an opportunity of hearing is void ab initio.",holding:"Every government servant is entitled to a fair hearing before an adverse order is passed against him.",applicability:"Binding on all service courts in disciplinary proceedings, termination challenges, and dismissal orders.",approved:true},

  {id:62,title:"Union of India v. Tulsiram Patel",citation:"(1985) 3 SCC 398",year:1985,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Service Law",area:"Service Law",tags:["Article 311","Dismissal","Departmental Enquiry","Service Rules","Constitutional Protection"],principle:"Article 311 protects civil servants from arbitrary dismissal. The right to be heard before dismissal is a constitutional right.",holding:"The constitutional protection of civil servants under Article 311 cannot be whittled down by service rules. Fair enquiry is mandatory.",applicability:"Applied in all cases challenging dismissal, removal, or reduction in rank of civil servants.",approved:true},

  {id:63,title:"M. Nagaraj v. Union of India",citation:"(2006) 8 SCC 212",year:2006,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Service Law",area:"Service Law",tags:["SC/ST Reservation","Promotion","Articles 16(4A)","Articles 16(4B)","Quantifiable Data","Three Conditions"],principle:"Reservation in promotion for SC/ST is valid only if the State establishes backwardness, inadequate representation, and that it will not affect efficiency.",holding:"Articles 16(4A) and 16(4B) allowing reservation in promotion are constitutionally valid subject to conditions.",applicability:"Applied in all cases involving reservation in promotions for SC/ST employees.",approved:true},

  {id:64,title:"Jarnail Singh v. Lachhmi Narain Gupta",citation:"(2018) 10 SCC 396",year:2018,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Service Law",area:"Service Law",tags:["SC/ST Promotion","Reservation","Creamy Layer","M. Nagaraj Modified","Inadequate Representation"],principle:"Creamy layer exclusion applies to SC/ST reservation in promotions. The test of backwardness in M. Nagaraj is modified.",holding:"States need not collect quantifiable data on backwardness for SC/ST promotion reservation. Inadequate representation is sufficient.",applicability:"Applied in all cases involving SC/ST promotion reservation and creamy layer exclusion.",approved:true},

  // ═══════════════════════════════════════════
  // ENVIRONMENTAL LAW
  // ═══════════════════════════════════════════

  {id:65,title:"M.C. Mehta v. Union of India (Absolute Liability)",citation:"AIR 1987 SC 1086 · (1987) 1 SCC 395",year:1987,bench:"5-Judge Bench",benchStrength:5,category:"Environmental Law",area:"Environmental Law",tags:["Absolute Liability","Hazardous Industry","Tort","No-Fault","No Exception"],principle:"Enterprises engaged in hazardous activity are absolutely liable to compensate for harm caused. No exception of Act of God or third party fault applies.",holding:"An enterprise engaged in hazardous or inherently dangerous industry owes an absolute and non-delegable duty to the community.",applicability:"Binding on all courts in environmental matters, industrial accident cases, and hazardous substance liability.",approved:true},

  {id:66,title:"Vellore Citizens' Welfare Forum v. Union of India",citation:"(1996) 5 SCC 647",year:1996,bench:"3-Judge Bench",benchStrength:3,category:"Environmental Law",area:"Environmental Law",tags:["Precautionary Principle","Polluter Pays","Sustainable Development","Environmental Law","Burden of Proof"],principle:"The precautionary principle and polluter pays principle are part of the law of the land. Sustainable development must be the guiding principle.",holding:"Industries causing pollution must pay for remediation. The burden of proof is on the industry to show its activity is environmentally safe.",applicability:"Applied in all environmental PIL cases and NGT matters. Foundational for Indian environmental jurisprudence.",approved:true},

  {id:67,title:"Subhash Kumar v. State of Bihar",citation:"AIR 1991 SC 420 · (1991) 1 SCC 598",year:1991,bench:"2-Judge Bench",benchStrength:2,category:"Environmental Law",area:"Environmental Law",tags:["Right to Clean Environment","Article 21","Water Pollution","PIL","Environmental Rights"],principle:"The right to live in a clean environment free from pollution is a fundamental right under Article 21.",holding:"Right to life includes the right to enjoy pollution-free water and air for full enjoyment of life.",applicability:"Applied in all environmental PILs and cases involving right to clean environment.",approved:true},

  {id:68,title:"M.C. Mehta v. Union of India (Taj Trapezium Case)",citation:"(1997) 2 SCC 353",year:1997,bench:"3-Judge Bench",benchStrength:3,category:"Environmental Law",area:"Environmental Law",tags:["Taj Mahal","Air Pollution","Heritage Protection","Relocate Industry","Precautionary Principle"],principle:"Protection of heritage monuments from environmental pollution is a constitutional imperative. Industries causing harm must be relocated.",holding:"Industries in Taj Trapezium Zone using coal/coke must switch to natural gas or relocate. The Taj Mahal must be protected.",applicability:"Applied in pollution control cases involving heritage sites and urban air quality matters.",approved:true},

  {id:69,title:"Union Carbide Corporation v. Union of India",citation:"(1989) 1 SCC 674",year:1989,bench:"5-Judge Bench",benchStrength:5,category:"Environmental Law",area:"Environmental Law",tags:["Bhopal Gas Tragedy","Multinational Corporation","Compensation","Industrial Disaster","Mass Tort"],principle:"A multinational corporation is liable for industrial disasters caused by its subsidiary in India. The State can represent victims in claims.",holding:"The settlement of ₹470 crore between UCC and Government of India was approved for victims of the Bhopal gas tragedy.",applicability:"Applied in cases involving mass tort liability of multinational corporations and industrial disasters.",approved:true},

  // ═══════════════════════════════════════════
  // FAMILY LAW
  // ═══════════════════════════════════════════

  {id:70,title:"Amardeep Singh v. Harveen Kaur",citation:"(2017) 8 SCC 746",year:2017,bench:"2-Judge Bench",benchStrength:2,category:"Family Law",area:"Family Law",tags:["Mutual Consent Divorce","Section 13B HMA","6-Month Cooling Period","Waiver","Irretrievable Breakdown"],principle:"The 6-month cooling period under Section 13B(2) HMA for mutual consent divorce is not mandatory and can be waived in appropriate cases.",holding:"Courts can waive the 6-month cooling period if the marriage has irretrievably broken down and the parties are firm in their decision.",applicability:"Applied in all mutual consent divorce petitions where waiver of cooling period is sought.",approved:true},

  {id:71,title:"V. Bhagat v. D. Bhagat",citation:"(1994) 1 SCC 337",year:1994,bench:"2-Judge Bench",benchStrength:2,category:"Family Law",area:"Family Law",tags:["Cruelty","Divorce","Mental Cruelty","Section 13(1)(ia) HMA","Apprehension"],principle:"Mental cruelty as ground for divorce includes conduct causing reasonable apprehension in the mind of the petitioner that it would be harmful to live with the respondent.",holding:"The court must consider social status, educational level, and conduct of the parties in determining mental cruelty for divorce.",applicability:"Applied in all divorce petitions on the ground of cruelty under Hindu Marriage Act.",approved:true},

  {id:72,title:"Githa Hariharan v. Reserve Bank of India",citation:"(1999) 2 SCC 228",year:1999,bench:"3-Judge Bench",benchStrength:3,category:"Family Law",area:"Family Law",tags:["Guardianship","Mother's Rights","Section 6 Hindu Minority Act","Article 14","Equal Rights"],principle:"Under Section 6 of the Hindu Minority and Guardianship Act, the mother's rights as natural guardian are equal to the father's.",holding:"The mother can act as natural guardian of a minor child in the absence of or when the father is incapable of acting as guardian.",applicability:"Applied in all guardianship matters involving rights of mothers over minor children.",approved:true},

  {id:73,title:"Shamima Farooqui v. Shahid Khan",citation:"(2015) 5 SCC 705",year:2015,bench:"2-Judge Bench",benchStrength:2,category:"Family Law",area:"Family Law",tags:["Maintenance","Section 125 CrPC","Muslim Women","Quantum","Standard of Living"],principle:"The quantum of maintenance must reflect the standard of living of the parties and the means of the husband, not just subsistence.",holding:"Maintenance under Section 125 CrPC must be sufficient to meet the reasonable needs of the wife and any dependent children.",applicability:"Applied in all maintenance applications under Section 125 CrPC across all courts.",approved:true},

  {id:74,title:"Rajesh Sharma v. State of U.P.",citation:"(2017) 11 SCC 1",year:2017,bench:"2-Judge Bench",benchStrength:2,category:"Family Law",area:"Criminal Law",tags:["Section 498A","Dowry Harassment","Misuse Prevention","Family Welfare Committees","No Automatic Arrest"],principle:"Laid down safeguards to prevent misuse of Section 498A IPC, including constitution of Family Welfare Committees.",holding:"Directions issued to prevent misuse of Section 498A including no automatic arrests, mandatory Family Welfare Committee report.",applicability:"Applied in all Section 498A cases regarding arrest procedure and bail. Note: Modified by subsequent orders.",approved:true},

  // ═══════════════════════════════════════════
  // PROPERTY LAW
  // ═══════════════════════════════════════════

  {id:75,title:"Bangalore Development Authority v. Syndicate Bank",citation:"(2007) 6 SCC 711",year:2007,bench:"2-Judge Bench",benchStrength:2,category:"Property Law",area:"Property Law",tags:["Land Acquisition","Compensation","Market Value","Section 23 LARR","Date of Notification"],principle:"Compensation for acquired land must be the market value at the time of acquisition notice, not at the time of award.",holding:"Under Section 23 of the Land Acquisition Act, compensation must be the market value of the land at the date of notification under Section 4.",applicability:"Applied in all land acquisition compensation disputes before courts and tribunals.",approved:true},

  {id:76,title:"Atma Ram Properties (P) Ltd. v. Federal Motors (P) Ltd.",citation:"(2005) 1 SCC 705",year:2005,bench:"3-Judge Bench",benchStrength:3,category:"Property Law",area:"Property Law",tags:["Rent Control","Eviction","Bona Fide Need","Landlord","Delhi Rent Control Act"],principle:"In eviction petitions on ground of personal need, the landlord must establish genuine and bona fide need for the premises.",holding:"The need of the landlord for the tenanted premises must be bona fide and real. The landlord need not exhaust all alternatives before filing eviction petition.",applicability:"Applied in all eviction cases on ground of bona fide need under various State Rent Control Acts.",approved:true},

  // ═══════════════════════════════════════════
  // LABOUR LAW
  // ═══════════════════════════════════════════

  {id:77,title:"Workmen of Hindustan Steel Ltd. v. Hindustan Steel Ltd.",citation:"(1984) 4 SCC 122",year:1984,bench:"2-Judge Bench",benchStrength:2,category:"Labour Law",area:"Labour Law",tags:["Reinstatement","Back Wages","Wrongful Termination","Labour Court","Normal Rule"],principle:"Reinstatement with full back wages is the normal remedy for wrongful termination unless special circumstances justify otherwise.",holding:"An employee wrongfully terminated is entitled to reinstatement with full back wages as the ordinary rule.",applicability:"Applied in industrial dispute cases involving wrongful termination and reinstatement.",approved:true},

  {id:78,title:"Bharat Petroleum Corporation Ltd. v. Maharashtra General Kamgar Union",citation:"(2008) 4 SCC 381",year:2008,bench:"2-Judge Bench",benchStrength:2,category:"Labour Law",area:"Labour Law",tags:["Contract Labour","Contract Workers","Regular Employment","Section 10 CLRA","No Automatic Absorption"],principle:"Abolition of contract labour under Section 10 of CLRA does not automatically entitle contract workers to regular employment.",holding:"Abolition of contract labour under Section 10 of CLRA does not create a right to absorption as regular employees.",applicability:"Applied in cases involving contract labour abolition and regularisation claims.",approved:true},

  // ═══════════════════════════════════════════
  // TAX LAW
  // ═══════════════════════════════════════════

  {id:79,title:"Commissioner of Income Tax v. Radha Krishan Industries",citation:"(2021) 6 SCC 693",year:2021,bench:"3-Judge Bench",benchStrength:3,category:"Tax Law",area:"Tax Law",tags:["Income Tax","Reassessment","Section 148","Reasons to Believe","Tangible Material","Change of Opinion"],principle:"The reasons to believe that income has escaped assessment must be based on tangible material and not a mere change of opinion.",holding:"Reassessment proceedings under Section 147/148 of the IT Act are valid only if the assessing officer has tangible material for formation of belief.",applicability:"Applied in all income tax reassessment challenges before ITAT and High Courts.",approved:true},

  {id:80,title:"Vodafone International Holdings BV v. Union of India",citation:"(2012) 6 SCC 613",year:2012,bench:"3-Judge Bench",benchStrength:3,category:"Tax Law",area:"Tax Law",tags:["Capital Gains","Non-Resident","Transfer of Shares","Section 9 IT Act","International Tax"],principle:"Transfer of shares of a foreign company holding Indian assets does not attract capital gains tax in India unless specifically provided.",holding:"The transfer of shares of a Cayman Islands company by a Netherlands company to an Indian telecom company is not taxable in India.",applicability:"Applied in international tax cases, cross-border transactions, and treaty interpretation.",approved:true},

  // ═══════════════════════════════════════════
  // COMPANY / COMMERCIAL / ARBITRATION LAW
  // ═══════════════════════════════════════════

  {id:81,title:"Sahara India Real Estate Corporation Ltd. v. SEBI",citation:"(2013) 1 SCC 1",year:2013,bench:"3-Judge Bench",benchStrength:3,category:"Company Law",area:"Company Law",tags:["SEBI","Public Issue","OFCDs","Collective Investment Scheme","₹24000 Crore Refund"],principle:"Optionally Fully Convertible Debentures offered to public at large fall within SEBI's regulatory purview and require compliance with securities laws.",holding:"SEBI has jurisdiction over public issues of OFCDs. Sahara directed to refund ₹24,000 crore to investors.",applicability:"Applied in cases involving jurisdiction of SEBI, definition of securities, and public issue compliance.",approved:true},

  {id:82,title:"Committee of Creditors of Essar Steel India Ltd. v. Satish Kumar Gupta",citation:"(2020) 8 SCC 531",year:2020,bench:"3-Judge Bench",benchStrength:3,category:"Company Law",area:"Company Law",tags:["IBC","Resolution Plan","CoC","Commercial Wisdom","Operational Creditors"],principle:"The Committee of Creditors has the commercial wisdom to approve resolution plans. Courts cannot interfere with commercial decisions of CoC.",holding:"The CoC's approval of resolution plan is final if it complies with mandatory requirements of IBC. Operational creditors cannot stall proceedings.",applicability:"Applied in all CIRP proceedings and challenges to resolution plans under IBC.",approved:true},

  {id:83,title:"BALCO v. Kaiser Aluminium & Chemical Corporation",citation:"(2012) 9 SCC 552",year:2012,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Arbitration Law",area:"Arbitration Law",tags:["International Arbitration","Part I","Part II","Arbitration Act","Foreign Seat","Jurisdiction"],principle:"Part I of the Arbitration Act does not apply to international commercial arbitrations seated outside India. Indian courts have limited jurisdiction.",holding:"Where the seat of arbitration is outside India, Indian courts have no jurisdiction to intervene in the arbitral process under Part I.",applicability:"Applied in all cases involving international commercial arbitration and jurisdiction of Indian courts.",approved:true},

  {id:84,title:"Perkins Eastman Architects DPC v. HSCC (India) Ltd.",citation:"(2020) 20 SCC 760",year:2020,bench:"2-Judge Bench",benchStrength:2,category:"Arbitration Law",area:"Arbitration Law",tags:["Appointment of Arbitrator","Section 11","Independence","Impartiality","Unilateral Appointment"],principle:"A person who has an interest in the outcome of a dispute cannot be permitted to unilaterally appoint an arbitrator.",holding:"The power to appoint an arbitrator cannot be exercised by an officer who himself is interested in the dispute.",applicability:"Applied in all cases involving challenge to unilateral appointment of arbitrators.",approved:true},

  {id:85,title:"Novartis AG v. Union of India",citation:"(2013) 6 SCC 1",year:2013,bench:"2-Judge Bench",benchStrength:2,category:"Intellectual Property",area:"Company Law",tags:["Patent","Section 3(d)","Evergreening","Generic Medicines","Glivec","Article 21"],principle:"Section 3(d) of the Patents Act prevents 'evergreening' of pharmaceutical patents by requiring genuine innovation for new patents.",holding:"Novartis' patent application for Glivec rejected as Section 3(d) prevents patenting of new forms of known substances without enhanced efficacy.",applicability:"Applied in pharmaceutical patent cases and challenges to new drug patents.",approved:true},

  {id:86,title:"Whirlpool Corporation v. Registrar of Trade Marks",citation:"(1998) 8 SCC 1",year:1998,bench:"3-Judge Bench",benchStrength:3,category:"Intellectual Property",area:"Company Law",tags:["Trademark","Trans-Border Reputation","Passing Off","Well-Known Mark","Foreign Company"],principle:"A foreign company with trans-border reputation can maintain a passing-off action in India even without prior registration in India.",holding:"Whirlpool has trans-border reputation in India and is entitled to protect its trademark against unauthorised use.",applicability:"Applied in all trademark infringement and passing-off cases involving foreign companies.",approved:true},

  // ═══════════════════════════════════════════
  // ELECTION LAW
  // ═══════════════════════════════════════════

  {id:87,title:"Kihoto Hollohan v. Zachillhu",citation:"1992 Supp (2) SCC 651",year:1992,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Election Law",area:"Election Law",tags:["Anti-Defection","Tenth Schedule","Speaker","Political Party","Para 7","Judicial Review"],principle:"The Tenth Schedule (anti-defection law) is constitutionally valid. However, the finality clause in Para 7 shielding the Speaker from judicial review is unconstitutional.",holding:"The decision of the Speaker on disqualification under the Tenth Schedule is subject to judicial review by High Courts and the Supreme Court.",applicability:"Applied in all anti-defection cases and disqualification proceedings under the Tenth Schedule.",approved:true},

  {id:88,title:"Lily Thomas v. Union of India",citation:"(2013) 7 SCC 653",year:2013,bench:"2-Judge Bench",benchStrength:2,category:"Election Law",area:"Election Law",tags:["Disqualification","Conviction","Section 8 RP Act","MPs","MLAs","Immediate Disqualification"],principle:"A sitting MP or MLA convicted of an offence with a sentence of 2 years or more stands immediately disqualified upon conviction.",holding:"Section 8(4) of the Representation of People Act 1951 giving protection to sitting legislators is unconstitutional.",applicability:"Binding on all authorities. Applied in cases involving disqualification of legislators on conviction.",approved:true},

  {id:89,title:"People's Union for Civil Liberties v. Union of India (NOTA)",citation:"(2013) 10 SCC 1",year:2013,bench:"2-Judge Bench",benchStrength:2,category:"Election Law",area:"Election Law",tags:["NOTA","Right to Vote","Negative Vote","Article 19","EVM","Right to Reject"],principle:"The right to vote includes the right to not vote for any candidate — the NOTA option must be provided in all elections.",holding:"The Election Commission must provide a NOTA option in EVMs to enable voters to exercise their right to reject all candidates.",applicability:"Applied in all election law matters involving voter rights and election procedure.",approved:true},

  // ═══════════════════════════════════════════
  // CONSUMER LAW
  // ═══════════════════════════════════════════

  {id:90,title:"Spring Meadows Hospital v. Harjol Ahluwalia",citation:"(1998) 4 SCC 39",year:1998,bench:"3-Judge Bench",benchStrength:3,category:"Consumer Law",area:"Consumer Law",tags:["Medical Negligence","Consumer Protection","NCDRC","Deficiency in Service","Hospital"],principle:"Medical services fall within the purview of the Consumer Protection Act. Medical negligence constitutes deficiency in service.",holding:"A hospital and its doctors providing medical services are 'service providers' under the Consumer Protection Act and patients are 'consumers'.",applicability:"Applied in all medical negligence cases before consumer forums and civil courts.",approved:true},

  {id:91,title:"Lucknow Development Authority v. M.K. Gupta",citation:"(1994) 1 SCC 243",year:1994,bench:"3-Judge Bench",benchStrength:3,category:"Consumer Law",area:"Consumer Law",tags:["Consumer Protection","Housing","Deficiency in Service","Statutory Bodies","Government Authority"],principle:"Statutory bodies and government authorities providing services are covered under the Consumer Protection Act.",holding:"The Consumer Protection Act applies to statutory and public authorities providing services. The LDA is liable for deficiency in housing services.",applicability:"Applied in all consumer complaints against government authorities and housing boards.",approved:true},

  // ═══════════════════════════════════════════
  // MOTOR ACCIDENT LAW
  // ═══════════════════════════════════════════

  {id:92,title:"Sarla Verma v. Delhi Transport Corporation",citation:"(2009) 6 SCC 121",year:2009,bench:"2-Judge Bench",benchStrength:2,category:"Motor Accident Law",area:"Motor Accident Law",tags:["MACT","Compensation","Motor Vehicle Act","Multiplier Method","Income","Dependency"],principle:"Laid down comprehensive guidelines for computation of compensation in motor accident cases using the multiplier method.",holding:"Standardised the multiplier method and deduction for personal expenses. Laid down dependency ratios for different categories of deceased.",applicability:"Binding on all Motor Accident Claims Tribunals and High Courts for computation of compensation.",approved:true},

  {id:93,title:"National Insurance Co. Ltd. v. Pranay Sethi",citation:"(2017) 16 SCC 680",year:2017,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Motor Accident Law",area:"Motor Accident Law",tags:["MACT","Compensation","Future Prospects","Motor Vehicle Act","40% Addition"],principle:"Future prospects must be added to the income of the deceased for computing just and fair compensation in motor accident cases.",holding:"Addition of 40% for future prospects for those below 40 years of age; 25% for those between 40-50 years.",applicability:"Binding on all MACT and High Courts in computation of motor accident compensation.",approved:true},

  // ═══════════════════════════════════════════
  // EDUCATION LAW
  // ═══════════════════════════════════════════

  {id:94,title:"T.M.A. Pai Foundation v. State of Karnataka",citation:"(2002) 8 SCC 481",year:2002,bench:"11-Judge Constitution Bench",benchStrength:11,category:"Education Law",area:"Constitutional Law",tags:["Right to Education","Article 30","Minority Institutions","Aided Institutions","Regulation","11-Judge Bench"],principle:"Minority institutions have the right to establish and administer educational institutions under Article 30. The State can regulate but not stifle this right.",holding:"Comprehensive directions on rights of minority and non-minority private educational institutions, including admission process and fee regulation.",applicability:"Applied in all cases involving regulation of private educational institutions and minority rights in education.",approved:true},

  {id:95,title:"Pramati Educational & Cultural Trust v. Union of India",citation:"(2014) 8 SCC 1",year:2014,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Education Law",area:"Constitutional Law",tags:["Right to Education","Article 21A","RTE Act","Private Schools","Minorities","25% Quota"],principle:"The Right to Education Act applies to aided and unaided non-minority schools. Minority schools are exempt from the RTE Act.",holding:"Section 12(1)(c) of the RTE Act directing private schools to admit 25% students from weaker sections is valid for non-minority schools.",applicability:"Applied in cases involving RTE Act compliance by private schools and minority school exemptions.",approved:true},

  // ═══════════════════════════════════════════
  // WRIT JURISDICTION
  // ═══════════════════════════════════════════

  {id:96,title:"Dwarka Nath v. Income Tax Officer",citation:"AIR 1966 SC 81",year:1966,bench:"3-Judge Bench",benchStrength:3,category:"Writ Law",area:"Constitutional Law",tags:["Article 226","High Court","Writ Jurisdiction","Broader Power","Any Direction"],principle:"Article 226 confers wide power to High Courts to issue any direction, order or writ — not confined to prerogative writs known to English law.",holding:"The High Court has power to issue any direction, order or writ to any authority or person within its territory.",applicability:"Applied in all writ petitions before High Courts. Establishes broad scope of writ jurisdiction under Article 226.",approved:true},

  {id:97,title:"State of U.P. v. Mohd. Nooh",citation:"AIR 1958 SC 86",year:1958,bench:"5-Judge Constitution Bench",benchStrength:5,category:"Writ Law",area:"Constitutional Law",tags:["Article 226","Certiorari","Broader than English Law","High Court Jurisdiction","Wider Scope"],principle:"High Court's power under Article 226 is wider than certiorari jurisdiction under English law. It can issue any appropriate writ.",holding:"The High Court can issue a writ of certiorari under Article 226 in cases beyond the scope of English certiorari.",applicability:"Applied in all writ petitions. Establishes broad jurisdiction of High Courts under Article 226.",approved:true},

  // ═══════════════════════════════════════════
  // RIGHT TO INFORMATION
  // ═══════════════════════════════════════════

  {id:98,title:"CBSE v. Aditya Bandopadhyay",citation:"(2011) 8 SCC 497",year:2011,bench:"3-Judge Bench",benchStrength:3,category:"Right to Information",area:"Constitutional Law",tags:["RTI","Answer Sheets","Inspection","Section 8 RTI Act","Public Authority","Examination"],principle:"Answer scripts and examination papers are public documents accessible under the RTI Act.",holding:"An examinee has the right to inspect his answer sheet under the RTI Act. Evaluated answer scripts are documents held by a public authority.",applicability:"Applied in all RTI cases involving inspection of answer sheets and examination documents.",approved:true},

  {id:99,title:"Secretary General, Supreme Court of India v. Subhash Chandra Agarwal",citation:"(2010) 1 SCC 288",year:2010,bench:"3-Judge Bench",benchStrength:3,category:"Right to Information",area:"Constitutional Law",tags:["RTI","Judiciary","Judges Assets","CJI Office","Public Authority","Transparency"],principle:"The office of the Chief Justice of India is a public authority under the RTI Act and is subject to disclosure requirements.",holding:"The Supreme Court is a public authority under the RTI Act. Information about assets of judges is not exempt from disclosure.",applicability:"Applied in RTI cases involving disclosures about the judiciary and judicial appointments.",approved:true},

  // ═══════════════════════════════════════════
  // CHILD RIGHTS & JUVENILE JUSTICE
  // ═══════════════════════════════════════════

  {id:100,title:"Bachpan Bachao Andolan v. Union of India",citation:"(2011) 5 SCC 1",year:2011,bench:"2-Judge Bench",benchStrength:2,category:"Child Rights",area:"Constitutional Law",tags:["Child Labour","Article 24","Circus","Child Rights","Hazardous Employment"],principle:"Children cannot be employed in circuses or similar hazardous occupations. The State must take active steps to eliminate child labour.",holding:"Directions issued for rescue and rehabilitation of children employed in circuses. Comprehensive guidelines for eliminating child labour.",applicability:"Applied in cases involving child labour, employment of children in hazardous activities, and child rights matters.",approved:true},

  {id:101,title:"Shakti Vahini v. Union of India",citation:"(2018) 7 SCC 192",year:2018,bench:"3-Judge Bench",benchStrength:3,category:"Constitutional Law",area:"Constitutional Law",tags:["Honour Killing","Khap Panchayats","Article 21","Article 19","Right to Choose Spouse","Adults"],principle:"The right to choose a spouse is a fundamental right under Articles 19 and 21. Khap panchayats and honour killings are unconstitutional.",holding:"Comprehensive directions issued against honour killing and interference by caste panchayats in the marriage choices of adults.",applicability:"Applied in cases involving honour killing, interference with marriage choices, and khap panchayat activities.",approved:true},

  {id:102,title:"Nandini Sundar v. State of Chhattisgarh",citation:"(2011) 7 SCC 547",year:2011,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Salwa Judum","SPOs","Armed Militias","Article 14","Article 21","Rule of Law"],principle:"The State cannot arm civilians to fight Maoists. Such armed militias violate the right to equality and right to life.",holding:"Salwa Judum militia in Chhattisgarh is unconstitutional. Special Police Officers cannot be deployed in counter-insurgency operations.",applicability:"Applied in cases involving use of civilian militias by State and their constitutional validity.",approved:true},

  {id:103,title:"Re: Ramlila Maidan Incident",citation:"(2012) 5 SCC 1",year:2012,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Right to Protest","Article 19","Assembly","Police Action","Peaceful Assembly","Night Action"],principle:"Citizens have a fundamental right to peaceful protest. Police cannot disperse peaceful protestors without lawful justification.",holding:"Police action at Ramlila Maidan dispersing peaceful gathering violated Articles 19 and 21.",applicability:"Applied in cases involving right to protest, peaceful assembly, and police action against protesters.",approved:true},

  // OVERRULED CASES
  {id:104,title:"Suresh Kumar Koushal v. Naz Foundation",citation:"(2014) 1 SCC 1",year:2014,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Section 377","OVERRULED","Homosexuality","Article 14","Article 21"],principle:"OVERRULED — This judgment held Section 377 IPC to be constitutional. It was overruled by Navtej Singh Johar v. Union of India (2018).",holding:"OVERRULED by Navtej Singh Johar (2018). Do not cite this as binding precedent.",applicability:"NOT applicable as binding precedent. OVERRULED by Navtej Singh Johar v. Union of India (2018) 10 SCC 1. Navtej Singh Johar is the binding precedent.",approved:false,overruledBy:"Navtej Singh Johar v. Union of India (2018) 10 SCC 1"},

  {id:105,title:"P. Rathinam v. Union of India",citation:"(1994) 3 SCC 394",year:1994,bench:"2-Judge Bench",benchStrength:2,category:"Constitutional Law",area:"Constitutional Law",tags:["Section 309 IPC","Attempt to Suicide","Right to Die","Article 21","OVERRULED"],principle:"OVERRULED — This case held Section 309 IPC to be unconstitutional. It was overruled by Gian Kaur v. State of Punjab (1996).",holding:"OVERRULED by Gian Kaur v. State of Punjab (1996) 2 SCC 648. Section 309 has since been decriminalised by Mental Healthcare Act 2017.",applicability:"NOT applicable as binding precedent. OVERRULED. Note that Section 309 has been decriminalised by Mental Healthcare Act 2017.",approved:false,overruledBy:"Gian Kaur v. State of Punjab (1996) 2 SCC 648"},

]

export const PRECEDENT_CATEGORIES = [
  "All",
  "Constitutional Law",
  "Criminal Law",
  "Civil Law",
  "Administrative Law",
  "Service Law",
  "Property Law",
  "Family Law",
  "Labour Law",
  "Tax Law",
  "Environmental Law",
  "Company Law",
  "Arbitration Law",
  "Media Law",
  "Election Law",
  "Consumer Law",
  "Motor Accident Law",
  "Intellectual Property",
  "Education Law",
  "Prison Law",
  "Child Rights",
  "Right to Information",
  "Juvenile Justice",
  "Writ Law",
]
